version: '2'
services:
  web:
    build:
      # args:
      #   bundle_path: /bundle
      context: .
      dockerfile: Dockerfile
    command: sh /entrypoint.sh
    volumes:
      - .:/app
      - ./conf/entrypoint/web.sh:/entrypoint.sh
      - ./conf/config/unicorn/production.rb:/app/config/unicorn/production.rb
      - ./conf/config/database.yml:/app/config/database.yml
      - ./conf/config/newrelic.yml:/app/config/newrelic.yml
      - ./conf/config/services.yml:/app/config/services.yml
      - ./conf/config/storage.yml:/app/config/storage.yml
      - bundle_cache:/bundle
      - web_log:/app/log
      - web_tmp:/app/tmp
      - file_storage:/app/public/system/
      - assets:/app/public/assets/
      - web_public:/app/public
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: mysql2://root@mysql/nazgrel_development
  cron:
    build: .
    command: sh /entrypoint.sh
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
      - ./conf/entrypoint/cron.sh:/entrypoint.sh
      - ./conf/config/unicorn/production.rb:/app/config/unicorn/production.rb
      - ./conf/config/database.yml:/app/config/database.yml
      - ./conf/config/newrelic.yml:/app/config/newrelic.yml
      - ./conf/config/services.yml:/app/config/services.yml
      - ./conf/config/storage.yml:/app/config/storage.yml
      - bundle_cache:/bundle
      - cron_log:/app/log
      - cron_tmp:/app/tmp
      - file_storage:/app/public/system/
    # volumes_from:
    #  - web
    environment:
      DATABASE_URL: mysql2://root@mysql/nazgrel_development
  sidekiq:
    build: .
    command: sh /entrypoint.sh
    restart: always
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
      - ./conf/entrypoint/sidekiq.sh:/entrypoint.sh
      - ./conf/config/unicorn/production.rb:/app/config/unicorn/production.rb
      - ./conf/config/database.yml:/app/config/database.yml
      - ./conf/config/newrelic.yml:/app/config/newrelic.yml
      - ./conf/config/services.yml:/app/config/services.yml
      - ./conf/config/storage.yml:/app/config/storage.yml
      - bundle_cache:/bundle
      - sidekiq_log:/app/log
      - sidekiq_tmp:/app/tmp
      - file_storage:/app/public/system/
    # volumes_from:
    #   - web
    environment:
      DATABASE_URL: mysql2://root@mysql/nazgrel_development
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - web_public:/app/public/
    ports:
      - 80:80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: nazgrelmysql
  redis:
    image: redis:3.2
volumes:
  bundle_cache:
  file_storage:
  assets:
  web_public:
  web_log:
  web_tmp:
  cron_log:
  cron_tmp:
  sidekiq_log:
  sidekiq_tmp: