shop_seek_job:
  cron: "*/5 * * * *"
  name: "同步店铺"
  class: "ShopSeekWorker"
  queue: :seek

shopkeeper_seek_job:
  cron: "*/30 * * * *"
  name: "同步店主"
  class: "ShopkeeperSeekWorker"
  queue: :seek

order_seek_job:
  cron: "*/30 * * * *"
  name: "同步订单"
  class: "OrderSeekWorker"
  queue: :seek

order_seek_job:
  cron: "*/30 * * * *"
  name: "同步订单"
  class: "ProductSeekWorker"
  queue: :seek

income_record_seek_job:
  cron: "*/5 * * * *"
  name: "同步收入记录"
  class: "IncomeRecordSeekWorker"
  queue: :seek
