shop_seek_job:
  cron: "*/1 * * * *"
  name: "同步店铺"
  class: "ShopSeekWorker"
  queue: :seek
  args:
    duration: 3
# # NOTICE 已经在同步店铺的时候处理
# shopkeeper_seek_job:
#   cron: "*/1 * * * *"
#   name: "同步店主"
#   class: "ShopkeeperSeekWorker"
#   queue: :seek
#   args:
#     duration: 3

order_seek_job:
  cron: "*/1 * * * *"
  name: "同步订单"
  class: "OrderSeekWorker"
  queue: :seek
  args:
    duration: 3
order_detail_seek_job:
  cron: "*/1 * * * *"
  name: "同步订单详情"
  class: "OrderDetailSeekWorker"
  queue: :seek
  args:
    duration: 3
order_sub_seek_job:
  cron: "*/1 * * * *"
  name: "同步子订单"
  class: "OrderSubSeekWorker"
  queue: :seek
  args:
    duration: 3
order_express_seek_job:
  cron: "*/1 * * * *"
  name: "同步物流订单"
  class: "OrderExpressSeekWorker"
  queue: :seek
  args:
    duration: 3
order_pay_seek_job:
  cron: "*/1 * * * *"
  name: "同步订单支付记录"
  class: "OrderPaySeekWorker"
  queue: :seek
  args:
    duration: 3
order_refund_seek_job:
  cron: "*/1 * * * *"
  name: "同步退款订单"
  class: "OrderRefundSeekWorker"
  queue: :seek
  args:
    duration: 3
order_refund_express_seek_job:
  cron: "*/1 * * * *"
  name: "同步退款物流订单"
  class: "OrderRefundExpressSeekWorker"
  queue: :seek
  args:
    duration: 3
order_refund_pay_seek_job:
  cron: "*/1 * * * *"
  name: "同步退款订单支付记录"
  class: "OrderRefundPaySeekWorker"
  queue: :seek
  args:
    duration: 3
order_refund_product_detail_seek_job:
  cron: "*/1 * * * *"
  name: "同步退款订单商品详情"
  class: "OrderRefundProductDetailSeekWorker"
  queue: :seek
  args:
    duration: 3
order_refund_icon_seek_job:
  cron: "*/1 * * * *"
  name: "同步退款订单图片"
  class: "OrderRefundIconSeekWorker"
  queue: :seek
  args:
    duration: 3
product_seek_job:
  cron: "*/1 * * * *"
  name: "同步商品"
  class: "ProductSeekWorker"
  queue: :seek
  args:
    duration: 3
product_shop_seek_job:
  cron: "*/1 * * * *"
  name: "同步店铺代理销售商品"
  class: "ProductShopSeekWorker"
  queue: :seek
  args:
    duration: 3
income_record_seek_job:
  cron: "*/1 * * * *"
  name: "同步收入记录"
  class: "IncomeRecordSeekWorker"
  queue: :seek
  args:
    duration: 3
withdraw_record_seek_job:
  cron: "*/1 * * * *"
  name: "同步提现记录"
  class: "WithdrawRecordSeekWorker"
  queue: :seek
  args:
    duration: 3
invite_pay_record_seek_job:
  cron: "*/1 * * * *"
  name: "同步邀请支付记录"
  class: "InvitePayRecordSeekWorker"
  queue: :seek
  args:
    duration: 3
shop_user_seek_job:
  cron: "*/1 * * * *"
  name: "同步用户信息"
  class: "ShopUserSeekWorker"
  queue: :seek
  args:
    duration: 3
shop_user_card_seek_job:
  cron: "*/1 * * * *"
  name: "同步用户身份证信息"
  class: "ShopUserCardSeekWorker"
  queue: :seek
  args:
    duration: 3
user_address_seek_job:
  cron: "*/1 * * * *"
  name: "同步用户收货地址"
  class: "UserAddressSeekWorker"
  queue: :seek
  args:
    duration: 3
bank_card_seek_job:
  cron: "*/1 * * * *"
  name: "同步银行卡"
  class: "BankCardSeekWorker"
  queue: :seek
  args:
    duration: 3
shop_wechat_user_seek_job:
  cron: "*/1 * * * *"
  name: "同步微信用户信息"
  class: "ShopWechatUserSeekWorker"
  queue: :seek
  args:
    duration: 3
supplier_seek_job:
  cron: "*/10 * * * *"
  name: "同步供应商"
  class: "SupplierSeekWorker"
  queue: :seek
  args:
    duration: 15

view_journal_seek_job:
  cron: "*/1 * * * *"
  name: "同步店铺浏览日志"
  class: "ViewJournalSeekWorker"
  queue: :seek
  args:
    duration: 3

share_journal_seek_job:
  cron: "*/1 * * * *"
  name: "同步店铺分享日志"
  class: "ShareJournalSeekWorker"
  queue: :seek
  args:
    duration: 3

category_seek_job:
  cron: "1 */2 * * *"
  name: "同步类别"
  class: "CategorySeekWorker"
  queue: :seek
  args:
    duration: 125
bank_seek_job:
  cron: "1 */2 * * *"
  name: "同步银行"
  class: "BankSeekWorker"
  queue: :seek
  args:
    duration: 125
product_sku_seek_job:
  cron: "*/1 * * * *"
  name: "同步产品库存"
  class: "ProductSkuSeekWorker"
  queue: :seek
  args:
    duration: 3

act_ticket_seek_job:
  cron: "*/1 * * * *"
  name: "同步券"
  class: "ActTicketSeekWorker"
  queue: :seek
  args:
    duration: 3

act_ticket_activity_seek_job:
  cron: "*/1 * * * *"
  name: "同步券活动"
  class: "ActTicketActivitySeekWorker"
  queue: :seek
  args:
    duration: 3

act_user_ticket_seek_job:
  cron: "*/1 * * * *"
  name: "同步券"
  class: "ActUserTicketSeekWorker"
  queue: :seek
  args:
    duration: 3

deleted_record_seek_job:
  cron: "3 * * * *"
  name: "删除芝蚂城已经删除的记录"
  class: "DeletedRecordSeekWorker"
  queue: :seek
  args:
    duration: 125

channel_shop_newer_report_partial:
  cron: "*/15 * * * *"
  name: "实时更新渠道新增报表"
  class: "ChannelShopNewerReportWorker"
  queue: :report
  args:
    type: "partial"

# shop_activity_report:
#   cron: "31 10,23 * * *"
#   name: "全量当天更新店主行为报表"
#   class: "ShopActivityReportWorker"
#   queue: :report
#   args:
#     type: "whole"
shop_activity_report_partial:
  cron: "*/3 * * * *"
  name: "实时更新店主行为数据"
  class: "ShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

shop_ecn_report_partial:
  cron: "*/15 * * * *"
  name: "实时更新店主ECN数据"
  class: "ShopEcnReportWorker"
  queue: :report
  args:
    type: "partial"

city_shop_activity_report_partial:
  cron: "*/3 * * * *"
  name: "实时更新城市店主行为数据"
  class: "CityShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

channel_shop_activity_report_partial:
  cron: "*/8 * * * *"
  name: "实时更新城市店主行为数据"
  class: "ChannelShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

cumulative_shop_activity_report_update_inactive:
  cron: "03 00 * * *"
  name: "重置当天累计店主行为数据"
  class: "CumulativeShopActivityReportWorker"
  queue: :report
  args:
    type: "update_old"
cumulative_shop_activity_report_partial:
  cron: "*/3 * * * *"
  name: "实时更新累计店主行为数据"
  class: "CumulativeShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

daily_operational_report:
  cron: "*/10 * * * *"
  name: "更新当天每日运营报表数据"
  class: "DailyOperationalReportWorker"
  queue: :report
  args:
    type: "today"
daily_operational_report_yesterday:
  cron: "3 0 * * *"
  name: "更新昨天每日运营报表数据"
  class: "DailyOperationalReportWorker"
  queue: :report
  args:
    type: "yesterday"

daily_shop_grade_operational_report:
  cron: "*/10 * * * *"
  name: "更新当天每日店主等级运营报表数据"
  class: "DailyShopGradeOperationalReportWorker"
  queue: :report
  args:
    type: "today"
daily_shop_grade_operational_report_yesterday:
  cron: "3 0 * * *"
  name: "更新昨天每日店主等级运营报表数据"
  class: "DailyShopGradeOperationalReportWorker"
  queue: :report
  args:
    type: "yesterday"

daily_operational_shop_grade_summary_report:
  cron: "*/10 * * * *"
  name: "更新当天每日运营店主等级汇总报表数据"
  class: "DailyOperationalShopGradeSummaryReportWorker"
  queue: :report
  args:
    type: "today"
daily_operational_shop_grade_summary_report_yesterday:
  cron: "3 0 * * *"
  name: "更新昨天每日运营店主等级汇总报表数据"
  class: "DailyOperationalShopGradeSummaryReportWorker"
  queue: :report
  args:
    type: "yesterday"

operational_cumulative_shop_activity_summary_report:
  cron: "*/10 * * * *"
  name: "更新当天运营店主活跃汇总报表数据"
  class: "OperationalCumulativeShopActivitySummaryReportWorker"
  queue: :report
  args:
    type: "today"
operational_cumulative_shop_activity_summary_report_yesterday:
  cron: "3 0 * * *"
  name: "更新昨天运营店主活跃汇总报表数据"
  class: "OperationalCumulativeShopActivitySummaryReportWorker"
  queue: :report
  args:
    type: "yesterday"