shop_seek_job:
  cron: "*/5 * * * *"
  name: "同步店铺"
  class: "ShopSeekWorker"
  queue: :seek
  args:
    duration: 8
# # NOTICE 已经在同步店铺的时候处理
# shopkeeper_seek_job:
#   cron: "*/15 * * * *"
#   name: "同步店主"
#   class: "ShopkeeperSeekWorker"
#   queue: :seek
#   args:
#     duration: 900

order_seek_job:
  cron: "*/15 * * * *"
  name: "同步订单"
  class: "OrderSeekWorker"
  queue: :seek
  args:
    duration: 18
order_detail_seek_job:
  cron: "*/15 * * * *"
  name: "同步订单"
  class: "OrderDetailSeekWorker"
  queue: :seek
  args:
    duration: 18
order_sub_seek_job:
  cron: "*/15 * * * *"
  name: "同步子订单"
  class: "OrderSubSeekWorker"
  queue: :seek
  args:
    duration: 18
order_express_seek_job:
  cron: "*/15 * * * *"
  name: "同步物流订单"
  class: "OrderExpressSeekWorker"
  queue: :seek
  args:
    duration: 18
product_seek_job:
  cron: "*/15 * * * *"
  name: "同步商品"
  class: "ProductSeekWorker"
  queue: :seek
  args:
    duration: 18
product_shop_seek_job:
  cron: "*/15 * * * *"
  name: "同步店铺代理销售商品"
  class: "ProductShopSeekWorker"
  queue: :seek
  args:
    duration: 18
income_record_seek_job:
  cron: "*/5 * * * *"
  name: "同步收入记录"
  class: "IncomeRecordSeekWorker"
  queue: :seek
  args:
    duration: 8
invite_pay_record_seek_job:
  cron: "*/5 * * * *"
  name: "同步邀请支付记录"
  class: "InvitePayRecordSeekWorker"
  queue: :seek
  args:
    duration: 8
shop_user_seek_job:
  cron: "*/15 * * * *"
  name: "同步用户信息"
  class: "ShopUserSeekWorker"
  queue: :seek
  args:
    duration: 18
shop_wechat_user_seek_job:
  cron: "*/15 * * * *"
  name: "同步微信用户信息"
  class: "ShopWechatUserSeekWorker"
  queue: :seek
  args:
    duration: 18
supplier_seek_job:
  cron: "*/30 * * * *"
  name: "同步供应商"
  class: "SupplierSeekWorker"
  queue: :seek
  args:
    duration: 35

view_journal_seek_job:
  cron: "*/30 * * * *"
  name: "同步店铺浏览日志"
  class: "ViewJournalSeekWorker"
  queue: :seek
  args:
    duration: 35

share_journal_seek_job:
  cron: "*/30 * * * *"
  name: "同步店铺分享日志"
  class: "ShareJournalSeekWorker"
  queue: :seek
  args:
    duration: 35

category_seek_job:
  cron: "1 */2 * * *"
  name: "同步类别"
  class: "CategorySeekWorker"
  queue: :seek
  args:
    duration: 125

product_sku_seek_job:
  cron: "*/30 * * * *"
  name: "同步产品库存"
  class: "ProductSkuSeekWorker"
  queue: :seek
  args:
    duration: 35

act_ticket_seek_job:
  cron: "*/30 * * * *"
  name: "同步券"
  class: "ActTicketSeekWorker"
  queue: :seek
  args:
    duration: 35

deleted_record_seek_job:
  cron: "3 * * * *"
  name: "删除芝蚂城已经删除的记录"
  class: "DeletedRecordSeekWorker"
  queue: :seek
  args:
    duration: 125

channel_shop_newer_report:
  cron: "51 11,23 * * *"
  name: "全量当天更新渠道新增报表"
  class: "ChannelShopNewerReportWorker"
  queue: :report
  args:
    type: "whole"
channel_shop_newer_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新渠道新增报表"
  class: "ChannelShopNewerReportWorker"
  queue: :report
  args:
    type: "partial"

shop_activity_report:
  cron: "31 10,23 * * *"
  name: "全量当天更新店主行为报表"
  class: "ShopActivityReportWorker"
  queue: :report
  args:
    type: "whole"
shop_activity_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新店主行为数据"
  class: "ShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

shop_ecn_report:
  cron: "31 10,23 * * *"
  name: "全量当天更新店主ECN报表"
  class: "ShopEcnReportWorker"
  queue: :report
  args:
    type: "whole"
shop_ecn_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新店主ECN数据"
  class: "ShopEcnReportWorker"
  queue: :report
  args:
    type: "partial"

city_shop_activity_report:
  cron: "41 11,23 * * *"
  name: "全量当天更新城市店主行为报表"
  class: "CityShopActivityReportWorker"
  queue: :report
  args:
    type: "whole"
city_shop_activity_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新城市店主行为数据"
  class: "CityShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

channel_shop_activity_report:
  cron: "43 11,23 * * *"
  name: "全量当天更新城市店主行为报表"
  class: "ChannelShopActivityReportWorker"
  queue: :report
  args:
    type: "whole"
channel_shop_activity_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新城市店主行为数据"
  class: "ChannelShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

cumulative_shop_activity_report_update_inactive:
  cron: "03 00 * * *"
  name: "重置当天累计店主行为数据"
  class: "CumulativeShopActivityReportWorker"
  queue: :report
  args:
    type: "update_old"
cumulative_shop_activity_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新累计店主行为数据"
  class: "CumulativeShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

daily_operational_report:
  cron: "1 */2 * * *"
  name: "更新当天每日运营报表数据"
  class: "DailyOperationalReportWorker"
  queue: :report
  args:
    type: "partial"