shop_seek_job:
  cron: "*/5 * * * *"
  name: "同步店铺"
  class: "ShopSeekWorker"
  queue: :seek
  args:
    duration: 8
# # NOTICE 已经在同步店铺的时候处理
# shopkeeper_seek_job:
#   cron: "*/15 * * * *"
#   name: "同步店主"
#   class: "ShopkeeperSeekWorker"
#   queue: :seek
#   args:
#     duration: 900

order_seek_job:
  cron: "*/15 * * * *"
  name: "同步订单"
  class: "OrderSeekWorker"
  queue: :seek
  args:
    duration: 18
order_detail_seek_job:
  cron: "*/15 * * * *"
  name: "同步订单"
  class: "OrderDetailSeekWorker"
  queue: :seek
  args:
    duration: 18
order_sub_seek_job:
  cron: "*/15 * * * *"
  name: "同步子订单"
  class: "OrderSubSeekWorker"
  queue: :seek
  args:
    duration: 18
order_sub_seek_job:
  cron: "*/15 * * * *"
  name: "同步物流订单"
  class: "OrderExpressSeekWorker"
  queue: :seek
  args:
    duration: 18
product_seek_job:
  cron: "*/15 * * * *"
  name: "同步商品"
  class: "ProductSeekWorker"
  queue: :seek
  args:
    duration: 18
product_shop_seek_job:
  cron: "*/15 * * * *"
  name: "同步店铺代理销售商品"
  class: "ProductShopSeekWorker"
  queue: :seek
  args:
    duration: 18
income_record_seek_job:
  cron: "*/5 * * * *"
  name: "同步收入记录"
  class: "IncomeRecordSeekWorker"
  queue: :seek
  args:
    duration: 8
shop_user_seek_job:
  cron: "*/15 * * * *"
  name: "同步用户信息"
  class: "ShopUserSeekWorker"
  queue: :seek
  args:
    duration: 18
shop_wechat_user_seek_job:
  cron: "*/15 * * * *"
  name: "同步微信用户信息"
  class: "ShopWechatUserSeekWorker"
  queue: :seek
  args:
    duration: 18
supplier_seek_job:
  cron: "*/30 * * * *"
  name: "同步供应商"
  class: "SupplierSeekWorker"
  queue: :seek
  args:
    duration: 35
category_seek_job:
  cron: "* */1 * * *"
  name: "同步类别"
  class: "CategorySeekWorker"
  queue: :seek
  args:
    type: "whole"

channel_shop_newer_report:
  cron: "51 11,23 * * *"
  name: "全量当天更新渠道新增报表"
  class: "ChannelShopNewerReportWorker"
  queue: :report
  args:
    type: "whole"
channel_shop_newer_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新渠道新增报表"
  class: "ChannelShopNewerReportWorker"
  queue: :report
  args:
    type: "partial"

shop_activity_report:
  cron: "31 10,23 * * *"
  name: "全量当天更新店主行为报表"
  class: "ShopActivityReportWorker"
  queue: :report
  args:
    type: "whole"
shop_activity_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新店主行为数据"
  class: "ShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

city_shop_activity_report:
  cron: "41 11,23 * * *"
  name: "全量当天更新城市店主行为报表"
  class: "CityShopActivityReportWorker"
  queue: :report
  args:
    type: "whole"
city_shop_activity_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新城市店主行为数据"
  class: "CityShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"

channel_shop_activity_report:
  cron: "43 11,23 * * *"
  name: "全量当天更新城市店主行为报表"
  class: "ChannelShopActivityReportWorker"
  queue: :report
  args:
    type: "whole"
channel_shop_activity_report_partial:
  cron: "*/30 * * * *"
  name: "实时更新城市店主行为数据"
  class: "ChannelShopActivityReportWorker"
  queue: :report
  args:
    type: "partial"