:concurrency: 5

:queues:
    - [low, 1]
    - [default, 5]
    - [high, 10]
    - [seek, 5]
    - [report, 3]

development:
  :concurrency: 10
staging:
  :concurrency: 10
production:
  :concurrency: 20